name: mirrorchyan_release

on:
  workflow_dispatch:
    inputs:
        tag:
            default: ''
            required: false
#   release:
#     types: [released]

jobs:
  mirrorchyan:
    if: ${{ github.repository_owner == 'AliceJump' }}
    runs-on: macos-latest

    steps:
      - uses: MirrorChyan/uploading-action@v1
        with:
          filetype: latest-release
          filename: "ok-ef-win32-China-setup-${{ inputs.tag }}.exe"
          mirrorchyan_rid: ok-end-field
          tag: ${{ inputs.tag }}

          os: ${{ matrix.os }}
          arch: ${{ matrix.arch }}

          owner: AliceJump
          repo: ok-end-field
          github_token: ${{ secrets.GITHUB_TOKEN }}
          upload_token: ${{ secrets.MirrorChyanUploadToken }}
